.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hyprdim 1  "hyprdim 2.0.1" 
.SH NAME
hyprdim \- Automatically dim windows in Hyprland when switching between them.
.SH SYNOPSIS
\fBhyprdim\fR [\fB\-s\fR|\fB\-\-strength\fR] [\fB\-d\fR|\fB\-\-duration\fR] [\fB\-f\fR|\fB\-\-fade\fR] [\fB\-b\fR|\fB\-\-bezier\fR] [\fB\-p\fR|\fB\-\-persist\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
.PP
hyprdim is a daemon that automatically dims windows in Hyprland[1] when
switching between them. It works by setting the dim_inactive[2] variable
and changing dim_strength[2] based on whether windows should be dimmed
or not. This enables hyprdim to have smooth dim animations. Additionally,
hyprdim makes use of threads to keep track of new window events. This
enables hyprdim to only disable dim once a user has been inactive long
enough.
.PP
hyprdim is written in Safe Rust[3] and is available under the MIT license[4].
Anyone is free to study the software and expand upon it. The source code is
available here[5].
.PP
[1]: https://hyprland.org/
.PP
[2]: https://wiki.hyprland.org/Configuring/Variables/
.PP
[3]: https://doc.rust\-lang.org/nomicon/meet\-safe\-and\-unsafe.html
.PP
[4]: https://raw.githubusercontent.com/donovanglover/hyprdim/master/LICENSE
.PP
[5]: https://github.com/donovanglover/hyprdim
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-strength\fR=\fISTRENGTH\fR [default: 0.4]
A value from 0 (no dim) to 1 (maximum dim)
.TP
\fB\-d\fR, \fB\-\-duration\fR=\fIDURATION\fR [default: 800]
How many milliseconds to wait
.TP
\fB\-f\fR, \fB\-\-fade\fR=\fIFADE\fR [default: 7]
Fade animation speed
.TP
\fB\-b\fR, \fB\-\-bezier\fR=\fIBEZIER\fR [default: default]
Bezier curve used for the animation
.TP
\fB\-p\fR, \fB\-\-persist\fR
Prevent dim_inactive from being disabled by `hyprctl reload` etc
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show information about what hyprdim is doing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v2.0.1
.SH AUTHORS
Copyright (C) 2023 Donovan Glover <https://donovan.is/>
